--DBA_ALURA01_CRIANDO DATABASE
CREATE DATABASE [dbVendas]
 ON  PRIMARY ( 
 NAME = N'dbVendas', 
 FILENAME = N'C:\DATA\ARQUIVO_DADOS\dbVendas.MDF', 
 SIZE = 100MB, 
 MAXSIZE = 200MB, 
 FILEGROWTH = 50MB )
 LOG ON ( 
 NAME = N'dbVendasLOG', 
 FILENAME = N'C:\DATA\LOG_TRANSACOES\dbVendasLOG.LDF', 
 SIZE = 100MB, 
 MAXSIZE = 200MB, 
 FILEGROWTH = 50MB );

 CREATE DATABASE [dbCustos]
 ON  PRIMARY ( 
 NAME = N'dbVendas', 
 FILENAME = N'C:\DATA\ARQUIVO_DADOS\dbCustos.MDF', 
 SIZE = 200MB,  
 FILEGROWTH = 25MB )
 LOG ON ( 
 NAME = N'dbVendasLOG', 
 FILENAME = N'C:\DATA\LOG_TRANSACOES\dbCustosLog.LDF', 
 SIZE = 100MB,  
 FILEGROWTH = 25MB );